"""Backend Suitability Estimator for Phase G6 Data-Driven Adaptive Work Routing.

Estimates the execution suitability [0.0, 1.0] of CPU and GPU execution backends
for a given workload unit, combining:
  1. Workload computational characteristics (WorkloadCostProfile)
  2. Host & accelerator runtime telemetry (ResourceSnapshot)
  3. Accelerator warm/cold compilation state
  4. Work backlog and queue saturation

Guarantees:
  - Zero leakage: No knowledge of future runtimes, oracle outcomes, or benchmark labels.
  - Mathematical transparency: Fully explainable scoring functions with audit breakdown.
  - Resilience: Safely handles missing/unavailable telemetry with graceful fallbacks.
"""

from __future__ import annotations

import logging
from dataclasses import asdict, dataclass, field
from typing import Any

from adaptive_framework.acceleration.workload_cost_model import WorkloadCostProfile
from adaptive_framework.models.runtime import ResourceSnapshot

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class BackendSuitabilityResult:
    """Calculated suitability scores and routing rationale.

    Attributes:
        cpu_score: Normalized suitability of CPU execution [0.0, 1.0].
        gpu_score: Normalized suitability of GPU execution [0.0, 1.0].
        confidence: Decision confidence margin in [0.0, 1.0].
        recommended_backend: Recommended backend ("CPU" or "GPU").
        primary_reason: Concise, human-readable rationale code.
        is_gpu_warm: Whether GPU was evaluated in pre-compiled warm state.
        factor_breakdown: Detailed sub-scores and discount factors.
    """

    cpu_score: float
    gpu_score: float
    confidence: float
    recommended_backend: str
    primary_reason: str
    is_gpu_warm: bool
    factor_breakdown: dict[str, float] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dictionary with rounded precision."""
        d = asdict(self)
        d["cpu_score"] = round(self.cpu_score, 4)
        d["gpu_score"] = round(self.gpu_score, 4)
        d["confidence"] = round(self.confidence, 4)
        return d

    def format_summary(self) -> str:
        """Format as a clean summary string."""
        return (
            f"Suitability(rec={self.recommended_backend}, conf={self.confidence:.2f}, "
            f"cpu={self.cpu_score:.3f}, gpu={self.gpu_score:.3f}, "
            f"warm={self.is_gpu_warm}, reason='{self.primary_reason}')"
        )


class BackendSuitabilityEstimator:
    """Evaluates relative suitability of CPU vs GPU backends."""

    def __init__(
        self,
        cold_start_amortization_pages: int = 15,
        gpu_overload_threshold_pct: float = 80.0,
        cpu_overload_threshold_pct: float = 85.0,
        min_gpu_free_mem_mb: float = 256.0,
        min_confidence: float = 0.15,
    ) -> None:
        """Initialize the suitability estimator with operational thresholds."""
        self._cold_amortization_pages = max(1, cold_start_amortization_pages)
        self._gpu_overload_pct = gpu_overload_threshold_pct
        self._cpu_overload_pct = cpu_overload_threshold_pct
        self._min_gpu_free_mem = min_gpu_free_mem_mb
        self._min_confidence = min_confidence

    def estimate_suitability(
        self,
        cost: WorkloadCostProfile,
        resource: ResourceSnapshot | None = None,
        is_gpu_warm: bool = True,
        queue_length: int = 0,
        active_workers: int = 1,
    ) -> BackendSuitabilityResult:
        """Calculate CPU and GPU suitability scores for the provided workload.

        Args:
            cost: WorkloadCostProfile generated by WorkloadCostEstimator.
            resource: Optional point-in-time ResourceSnapshot from G3 monitor.
            is_gpu_warm: Whether OpenVINO GPU model is already compiled and warm.
            queue_length: In-flight work queue depth.
            active_workers: Active parallel worker count.

        Returns:
            BackendSuitabilityResult with scores, confidence, and explanation.
        """
        # 1. Hardware Availability Checks
        gpu_detected = resource.gpu_available if resource else True
        if not gpu_detected:
            return BackendSuitabilityResult(
                cpu_score=1.0,
                gpu_score=0.0,
                confidence=1.0,
                recommended_backend="CPU",
                primary_reason="gpu_hardware_unavailable",
                is_gpu_warm=is_gpu_warm,
                factor_breakdown={"gpu_availability": 0.0},
            )

        # 2. Base Suitability from Workload Characteristics
        # High compute intensity & high pixel count strongly favor GPU parallelism.
        # Low intensity / small pages favor CPU (avoid dispatch overhead).
        intensity = cost.normalized_compute_intensity

        base_gpu = 0.20 + (0.75 * intensity)
        base_cpu = 0.85 - (0.65 * intensity)

        # 3. Dense Text / Token Recognition Adjustment
        # G5 showed that on very dense character layouts (Class C), CPU's sequential
        # token recognition performance remains competitive or superior to iGPU EUs.
        char_factor = cost.estimated_char_density
        if char_factor > 0.40 and intensity > 0.60:
            # Shift balance slightly towards CPU for dense textual records
            base_cpu += 0.12 * char_factor
            base_gpu -= 0.08 * char_factor

        # 4. Cold-Start Amortization Factor
        cold_discount = 1.0
        if not is_gpu_warm:
            # If GPU is cold, compilation penalty (~2.16s) must be amortized over batch size
            batch_ratio = min(1.0, cost.page_count / float(self._cold_amortization_pages))
            cold_discount = 0.35 + (0.65 * batch_ratio)
            base_gpu *= cold_discount

        # 5. Hardware Load & Resource Telemetry Adjustments
        gpu_load_discount = 1.0
        cpu_load_discount = 1.0

        if resource is not None:
            # GPU utilization penalty
            if resource.gpu_utilization_percent is not None:
                gpu_util = resource.gpu_utilization_percent
                if gpu_util > self._gpu_overload_pct:
                    excess = (gpu_util - self._gpu_overload_pct) / (100.0 - self._gpu_overload_pct)
                    gpu_load_discount = max(0.2, 1.0 - (0.8 * excess))
                    base_gpu *= gpu_load_discount

            # GPU memory constraint check
            if resource.gpu_memory_used_mb is not None and resource.gpu_memory_total_mb is not None:
                free_mem = resource.gpu_memory_total_mb - resource.gpu_memory_used_mb
                if free_mem < self._min_gpu_free_mem:
                    base_gpu *= 0.30

            # CPU utilization penalty
            cpu_util = resource.cpu_percent
            if cpu_util > self._cpu_overload_pct:
                excess_cpu = (cpu_util - self._cpu_overload_pct) / (100.0 - self._cpu_overload_pct)
                cpu_load_discount = max(0.2, 1.0 - (0.7 * excess_cpu))
                base_cpu *= cpu_load_discount

        # 6. Queue & Backlog Balancing
        effective_queue = max(queue_length, resource.queue_length if resource else 0)
        queue_discount_gpu = 1.0
        if effective_queue > 4 and gpu_load_discount < 0.8:
            # Heavy queue and busy GPU -> route more aggressively to CPU
            queue_discount_gpu = 0.85
            base_gpu *= queue_discount_gpu

        # 7. Clamp and Normalize Scores to [0.0, 1.0]
        final_gpu = max(0.05, min(0.98, base_gpu))
        final_cpu = max(0.05, min(0.98, base_cpu))

        # 8. Calculate Calibrated Confidence
        diff = abs(final_gpu - final_cpu)
        confidence = max(self._min_confidence, min(0.99, diff * 1.6 + 0.10))

        # 9. Determine Recommended Backend & Primary Reason
        if final_gpu > final_cpu:
            recommended = "GPU"
            if not is_gpu_warm and cost.page_count >= self._cold_amortization_pages:
                reason = "large_batch_amortizes_cold_gpu"
            elif intensity >= 0.50:
                reason = "high_compute_intensity_favors_gpu"
            elif cost.total_pixels >= 1500000:
                reason = "large_pixel_surface_favors_gpu"
            else:
                reason = "gpu_suitability_higher_than_cpu"
        else:
            recommended = "CPU"
            if not is_gpu_warm and cost.page_count < self._cold_amortization_pages:
                reason = "cold_gpu_overhead_unlikely_to_amortize"
            elif gpu_load_discount < 0.7:
                reason = "gpu_overloaded_routing_to_cpu"
            elif char_factor > 0.40 and intensity > 0.60:
                reason = "dense_text_layout_favors_cpu"
            elif intensity < 0.35:
                reason = "small_simple_page_favors_cpu"
            else:
                reason = "cpu_suitability_higher_than_gpu"

        factors = {
            "compute_intensity": round(intensity, 4),
            "char_factor": round(char_factor, 4),
            "cold_discount": round(cold_discount, 4),
            "gpu_load_discount": round(gpu_load_discount, 4),
            "cpu_load_discount": round(cpu_load_discount, 4),
            "queue_discount_gpu": round(queue_discount_gpu, 4),
            "raw_gpu": round(base_gpu, 4),
            "raw_cpu": round(base_cpu, 4),
        }

        return BackendSuitabilityResult(
            cpu_score=final_cpu,
            gpu_score=final_gpu,
            confidence=confidence,
            recommended_backend=recommended,
            primary_reason=reason,
            is_gpu_warm=is_gpu_warm,
            factor_breakdown=factors,
        )
